# Numpy
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [34]:
arr2 = np.array([[1,2,3,4],[11,22,33,44]])
print(type(arr2))
print(arr2.shape)
print(arr2.size)

<class 'numpy.ndarray'>
(2, 4)
8


In [18]:
arr3 = np.arange(12).reshape(4,3)
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
arr4 = np.array([0,1,2,3,16])
print(np.square(arr4))
print(np.sqrt(arr4))
print(np.cos(arr4))

[  0   1   4   9 256]
[ 0.          1.          1.41421356  1.73205081  4.        ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.95765948]


In [29]:
arr5 = np.array([1,2,3,4])
print(np.max(arr5))
print(np.min(arr5))
print(np.std(arr5))
print(np.mean(arr5))

4
1
1.11803398875
2.5


# Pandas